### ISSUE TITLE
Store the original SVG

### ISSUE THREAD

**Issue by jsorel** [Viglino/font-gis#13]
Would it be possible to have the original SVG aside the one's which are used for generation ?
This would be better when applying corrections and it would preserve the strokes.

we could have, something like :
- uEA92-compass-rose.svg
- uEA92-compass-rose.svg.orig

**Comment by Viglino** [comment]
It could be.
The generation process looks for the file with the .svg extenension. Other extensions will be ignored.
I think we could use .svgz extension to store original one (and make it readable directly).
