### ISSUE TITLE
Npm install problem

### ISSUE THREAD

**Issue by AntoniBCN** [Viglino/font-gis#3]
Hi,

I've installed using npm command in a Reactjs application but the following code desn't work:

<i className="fg-screen-split-h"></i>

But it works fine adding <link href="https://viglino.github.io/font-gis/css/font-gis.css" rel="stylesheet" /> in index.html

There's something more to do to use it with npm package instead to global css link?

Thank's a lot.

**Comment by Viglino** [comment]
Hi,
It's a font you just have to use it as other ones, including the css in your project...
You'll also need to serve the fonts themselves (ttf, woff, ...) from a folder called fonts/ in your public directory. 
I don't know how react handle this (or you have to copy those files manually)...

**Comment by AntoniBCN** [comment]
Hi,

I understand font-gis like others css frameworks. I use Semantic-ui-react and it works very simillar, and it's not necessary to make any other action than npm install...

Anyway, I'm new in React, and I'll explore more this litle issue.

Best regards
