### ISSUE TITLE
thickness of the paths

### ISSUE THREAD

**Issue by wilcar** [Viglino/font-gis#7]
hello, 
Could you tell me the thickness of the paths you used so that I can contribute? (in Adobe illustrator I found 6,3 pts)

**Comment by Viglino** [comment]
I use 7 px (using Inkscape) sometime 5 px (for thin lines) 
Canvas must be 100 x 100 px with 1 color, 1 shape.
![image](https://github.com/Viglino/font-gis/assets/7868217/90a642c4-d8b0-41ae-bca6-92bdccf6b6eb)
