### ISSUE TITLE
Coord-system-3d

### ISSUE THREAD

**Issue by Jochem-L** [Viglino/font-gis#8]
The icons coord-system-3d and coord-system-3d-alt are lefthanded, which means the y axis is found clockwise from the x axis instead of anticlockwise (when looking from above, in opposite direction as the z axis is pointing). This is very unusual for coordinate reference systems. I think this could best be fixed by switching the letters x and y in these two icons.

**Comment by Viglino** [comment]
Updated: https://github.com/Viglino/font-gis/commit/cdc4c3eab983db427da4036d7d675e14853bc0ce#diff-0a122fd41a95f1595350ae67b1fb106bf7a2b27202bfdb55ce87a560cb62b0e5
